project:
    type: book

book:
    title: "Git Notes"
    author: ""
    date: ""
    chapters:
        - index.qmd
        - setup.qmd

format:
    html:
        theme: cosmo
        toc-title: Contents
        link-external-newwindow: true



