project:
    type: book

book:
    title: "Git Notes"
    author: ""
    date: ""
    repo-url: https://github.com/Filebb/git-notes
    chapters:
        - index.qmd
        - setup.qmd
        - local-repo-basics.qmd
        - branching.qmd
        - references.qmd

format:
    html:
        theme: cosmo
        highlight-style: atom-one
        toc-title: Contents
        number-sections: false
        link-external-newwindow: true



