project:
    type: book

book:
    title: "Git Notes"
    author: ""
    date: ""
    chapters:
        - index.qmd
        - setup.qmd

format:
    html:
        theme: cosmo
        highlight-style: atom-one
        toc-title: Contents
        number-sections: false
        link-external-newwindow: true



