# Setup

## Install Git

### Windows

To install on Windows, download the executable from [here](https://git-scm.com/).

### Linux

To install on Debian based distros, run

```bash
sudo apt install git
```

## Update Git

On Windows, run the following command.

```bash
git update-git-for-windows
```

::: {.callout-note}
If you already have the latest version it just returns:
```bash
# Git for Windows 2.45.1.windows.1 (64-bit)
# Up to date
```
:::

## Version

The following command returns the version number currently installed.

```bash
git version
## git version 2.45.1.windows.1
```

::: {.callout-note}
Alternatively you can use `git -v` or `git --version`.
:::

## Setup Identity

Every Git commit uses your user name and email address. These can be set up
using the following commands.

```bash
git config --global user.name "<your name>"
git config --global user.email "<your email>"
```

You have to do this only once for any computer. You can also change them at any
time by running through the commands again.

## Setup Default Branch Name

By default Git creates a initial branch called `master`. To set a different
name, for example `main`, run:

```bash
git config --global init.defaultBranch main
```

## Check Your Settings

To check your settings use:

```bash
git config --global --list
# user.name=<your name>
# user.email=<your email>
# init.defaultbranch=main
```
